<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asignacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asignacion by idAsignacion
     */
    function get_asignacion($idAsignacion)
    {
        return $this->db->get_where('asignacion',array('idAsignacion'=>$idAsignacion))->row_array();
    }
        
    /*
     * Get all asignacion
     */
    function get_all_asignacion()
    {
        $this->db->order_by('idAsignacion', 'desc');
        return $this->db->get('asignacion')->result_array();
    }
        
    /*
     * function to add new asignacion
     */
    function add_asignacion($params)
    {
        $this->db->insert('asignacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asignacion
     */
    function update_asignacion($idAsignacion,$params)
    {
        $this->db->where('idAsignacion',$idAsignacion);
        return $this->db->update('asignacion',$params);
    }
    
    /*
     * function to delete asignacion
     */
    function delete_asignacion($idAsignacion)
    {
        return $this->db->delete('asignacion',array('idAsignacion'=>$idAsignacion));
    }
}
