<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get docente by idDocente
     */
    function get_docente($idDocente)
    {
        return $this->db->get_where('docente',array('idDocente'=>$idDocente))->row_array();
    }
        
    /*
     * Get all docente
     */
    function get_all_docente()
    {
        $this->db->order_by('idDocente', 'desc');
        return $this->db->get('docente')->result_array();
    }
        
    /*
     * function to add new docente
     */
    function add_docente($params)
    {
        $this->db->insert('docente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update docente
     */
    function update_docente($idDocente,$params)
    {
        $this->db->where('idDocente',$idDocente);
        return $this->db->update('docente',$params);
    }
    
    /*
     * function to delete docente
     */
    function delete_docente($idDocente)
    {
        return $this->db->delete('docente',array('idDocente'=>$idDocente));
    }

     /*
     * Get all docentes con sus datos personales
     */
    function get_all_docente_persona()
    {
        $this->db->from('docente d');
        $this->db->join('persona p', 'd.idPersona=p.idPersona','left');
        $this->db->join('escuelaProfesional ep', 'd.idEscuelaProfesional = ep.idEscuelaProfesional','left');
        $this->db->order_by('d.idDocente', 'desc');
        $this->db->limit(20);
        return $this->db->get()->result_array();
    }

    /*
     * Get docente y datos de persona by idDocente
     */
    function get_docente_persona($idDocente)
    {
        $this->db->from('docente d');
        $this->db->join('persona p', "d.idPersona=p.idPersona",'left');
        $this->db->join('escuelaProfesional ep', 'd.idEscuelaProfesional = ep.idEscuelaProfesional','left');
        return $this->db->get_where('docente',array('d.idDocente'=>$idDocente))->row_array();
    }

    /*
     * Get estudiantes con filtros
     */
    function filtroDocente($params){
        $this->db->join('persona p', 'd.idPersona=p.idPersona','left');
        $this->db->join('escuelaProfesional ep','d.idEscuelaProfesional=ep.idEscuelaProfesional','left');
        return $this->db->get_where('docente d',$params)->result_array();
    }
}
