<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Escuelaprofesional_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get escuelaprofesional by idEscuelaProfesional
     */
    function get_escuelaprofesional($idEscuelaProfesional)
    {
        return $this->db->get_where('escuelaprofesional',array('idEscuelaProfesional'=>$idEscuelaProfesional))->row_array();
    }
        
    /*
     * Get all escuelaprofesional
     */
    function get_all_escuelaprofesional()
    {
        $this->db->order_by('idEscuelaProfesional', 'desc');
        return $this->db->get('escuelaprofesional')->result_array();
    }

    /*
     * Get id, nombre from escuelaprofesional
     */
    function get_basic_escuelaprofesional()
    {
        $this->db->select('idEscuelaProfesional, nombreEscuelaProfesional');
        return $this->db->get('escuelaprofesional')->result_array();
    }
        
    /*
     * function to add new escuelaprofesional
     */
    function add_escuelaprofesional($params)
    {
        $this->db->insert('escuelaprofesional',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update escuelaprofesional
     */
    function update_escuelaprofesional($idEscuelaProfesional,$params)
    {
        $this->db->where('idEscuelaProfesional',$idEscuelaProfesional);
        return $this->db->update('escuelaprofesional',$params);
    }
    
    /*
     * function to delete escuelaprofesional
     */
    function delete_escuelaprofesional($idEscuelaProfesional)
    {
        return $this->db->delete('escuelaprofesional',array('idEscuelaProfesional'=>$idEscuelaProfesional));
    }
}
