<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by idEstudiante
     */
    function get_estudiante($idEstudiante)
    {
        return $this->db->get_where('estudiante',array('idEstudiante'=>$idEstudiante))->row_array();
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante()
    {
        $this->db->order_by('idEstudiante', 'desc');
        return $this->db->get('estudiante')->result_array();
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($idEstudiante,$params)
    {
        $this->db->where('idEstudiante',$idEstudiante);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($idEstudiante)
    {
        return $this->db->delete('estudiante',array('idEstudiante'=>$idEstudiante));
    }
    function get_estudiante_persona($idPersona)
    {
        return $this->db->get_where('estudiante',array('idPersona'=>$idPersona))->row_array();
    }
}
