<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Habilitacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get habilitacion by idHabilitacion
     */
    function get_habilitacion($idHabilitacion)
    {
        return $this->db->get_where('habilitacion',array('idHabilitacion'=>$idHabilitacion))->row_array();
    }
        
    /*
     * Get all habilitacion
     */
    function get_all_habilitacion()
    {
        $this->db->order_by('idHabilitacion', 'desc');
        return $this->db->get('habilitacion')->result_array();
    }
        
    /*
     * function to add new habilitacion
     */
    function add_habilitacion($params)
    {
        $this->db->insert('habilitacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update habilitacion
     */
    function update_habilitacion($idHabilitacion,$params)
    {
        $this->db->where('idHabilitacion',$idHabilitacion);
        return $this->db->update('habilitacion',$params);
    }
    
    /*
     * function to delete habilitacion
     */
    function delete_habilitacion($idHabilitacion)
    {
        return $this->db->delete('habilitacion',array('idHabilitacion'=>$idHabilitacion));
    }
}
