<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mcapacidade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mcapacidade by idMcapacidades
     */
    function get_mcapacidade($idMcapacidades)
    {
        return $this->db->get_where('mcapacidades',array('idMcapacidades'=>$idMcapacidades))->row_array();
    }
        
    /*
     * Get all mcapacidades
     */
    function get_all_mcapacidades()
    {
        $this->db->order_by('idMcapacidades', 'desc');
        return $this->db->get('mcapacidades')->result_array();
    }
        
    /*
     * function to add new mcapacidade
     */
    function add_mcapacidade($params)
    {
        $this->db->insert('mcapacidades',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mcapacidade
     */
    function update_mcapacidade($idMcapacidades,$params)
    {
        $this->db->where('idMcapacidades',$idMcapacidades);
        return $this->db->update('mcapacidades',$params);
    }
    
    /*
     * function to delete mcapacidade
     */
    function delete_mcapacidade($idMcapacidades)
    {
        return $this->db->delete('mcapacidades',array('idMcapacidades'=>$idMcapacidades));
    }
}
