<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modulo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modulo by idModulo
     */
    function get_modulo($idModulo)
    {
        return $this->db->get_where('modulo',array('idModulo'=>$idModulo))->row_array();
    }
        
    /*
     * Get all modulo
     */
    function get_all_modulo()
    {
        $this->db->order_by('idModulo', 'desc');
        return $this->db->get('modulo')->result_array();
    }
    /*
     * Get all modulo
     */
    function get_all_modulo_ep()
    {
        $this->db->select('m.idModulo, m.nombreModulo, m.horasModulo, m.idEscuelaProfesional, ep.nombreEscuelaProfesional');
        $this->db->from('modulo m');
        $this->db->join('escuelaProfesional ep', 'm.idEscuelaProfesional = ep.idEscuelaProfesional', 'left');
        $this->db->order_by('m.idModulo','DESC');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new modulo
     */
    function add_modulo($params)
    {
        $this->db->insert('modulo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modulo
     */
    function update_modulo($idModulo,$params)
    {
        $this->db->where('idModulo',$idModulo);
        return $this->db->update('modulo',$params);
    }
    
    /*
     * function to delete modulo
     */
    function delete_modulo($idModulo)
    {
        return $this->db->delete('modulo',array('idModulo'=>$idModulo));
    }

    /*
     * Get modulos por escuela profesional
     */
    function get_all_modulo_by_ep($idEscuelaProfesional)
    {
        $this->db->select('m.idModulo, m.nombreModulo, m.horasModulo, m.idEscuelaProfesional, ep.nombreEscuelaProfesional');
        $this->db->from('modulo m');
        $this->db->join('escuelaProfesional ep', 'm.idEscuelaProfesional = ep.idEscuelaProfesional', 'left');
        $this->db->where('m.idEscuelaProfesional', $idEscuelaProfesional);
        $this->db->order_by('idModulo', 'desc');
        return $this->db->get()->result_array();
    }

    /*
     * GEt modulo con campos de escuela profesional incluidos
     */

     function get_modulo_ep($idModulo){
         $this->db->from('modulo m');
         $this->db->join('escuelaprofesional ep','m.idEscuelaProfesional = ep.idEscuelaProfesional','left');
         $this->db->where('m.idModulo', $idModulo);
         $this->db->order_by('m.idModulo','DESC');
         return $this->db->get()->row_array();
     }

    /*
     * Get modulos correspondientes a un estudainte / solo los id y nombre de modulos
     */

     function get_modulosByEstudiante($idEstudiante){
         $this->db->select('m.idModulo, m.nombreModulo');
         $this->db->from('estudiante e');
         $this->db->join('escuelaProfesional ep', 'e.idEscuelaProfesional = ep.idEscuelaProfesional','left');
         $this->db->join('modulo m', 'ep.idEscuelaProfesional = m.idEscuelaProfesional','left');
         $this->db->where('e.idEstudiante',$idEstudiante);
         return $this->db->get()->result_array();
     }

}
