<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modulo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modulo by idModulo
     */
    function get_modulo($idModulo)
    {
        return $this->db->get_where('modulo',array('idModulo'=>$idModulo))->row_array();
    }
        
    /*
     * Get all modulo
     */
    function get_all_modulo()
    {
        $this->db->order_by('idModulo', 'desc');
        return $this->db->get('modulo')->result_array();
    }
        
    /*
     * function to add new modulo
     */
    function add_modulo($params)
    {
        $this->db->insert('modulo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modulo
     */
    function update_modulo($idModulo,$params)
    {
        $this->db->where('idModulo',$idModulo);
        return $this->db->update('modulo',$params);
    }
    
    /*
     * function to delete modulo
     */
    function delete_modulo($idModulo)
    {
        return $this->db->delete('modulo',array('idModulo'=>$idModulo));
    }

    /*
     * Get modulos por escuela profesional
     */
    function get_all_modulo_by_ep($idEscuelaProfesional)
    {
        $this->db->order_by('idModulo', 'desc');
        return $this->db->get_where('modulo', array('idEscuelaProfesional' => $idEscuelaProfesional))->result_array();
    }
}
