<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nota_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
        
    /*
     * function to add new Nota
     */
    function add_nota($params)
    {
        $this->db->insert('nota',$params);
        return $this->db->insert_id();
        // return $temp;
    }

}
