<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Permiso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get permiso by idPermiso
     */
    function get_permiso($idPermiso)
    {
        return $this->db->get_where('permisos',array('idPermiso'=>$idPermiso))->row_array();
    }
        
    /*
     * Get all permisos
     */
    function get_all_permisos()
    {
        $this->db->order_by('idPermiso', 'desc');
        return $this->db->get('permisos')->result_array();
    }
        
    /*
     * function to add new permiso
     */
    function add_permiso($params)
    {
        $this->db->insert('permisos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update permiso
     */
    function update_permiso($idPermiso,$params)
    {
        $this->db->where('idPermiso',$idPermiso);
        return $this->db->update('permisos',$params);
    }
    
    /*
     * function to delete permiso
     */
    function delete_permiso($idPermiso)
    {
        return $this->db->delete('permisos',array('idPermiso'=>$idPermiso));
    }
}
