<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plazomatricula_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plazomatricula by idPlazoMatricula
     */
    function get_plazomatricula($idPlazoMatricula)
    {
        return $this->db->get_where('plazomatricula',array('idPlazoMatricula'=>$idPlazoMatricula))->row_array();
    }
        
    /*
     * Get all plazomatricula
     */
    function get_all_plazomatricula()
    {
        $this->db->order_by('idPlazoMatricula', 'desc');
        return $this->db->get('plazomatricula')->result_array();
    }
        
    /*
     * function to add new plazomatricula
     */
    function add_plazomatricula($params)
    {
        $this->db->insert('plazomatricula',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plazomatricula
     */
    function update_plazomatricula($idPlazoMatricula,$params)
    {
        $this->db->where('idPlazoMatricula',$idPlazoMatricula);
        return $this->db->update('plazomatricula',$params);
    }
    
    /*
     * function to delete plazomatricula
     */
    function delete_plazomatricula($idPlazoMatricula)
    {
        return $this->db->delete('plazomatricula',array('idPlazoMatricula'=>$idPlazoMatricula));
    }
}
