<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plazonota_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plazonota by idPlazoNotas
     */
    function get_plazonota($idPlazoNotas)
    {
        $this->db->from('plazonotas pn');
        $this->db->join('semestreAcademico sa', 'pn.idSemestreAcademico = sa.idSemestreAcademico','left');
        $this->db->where('pn.idPlazoNotas',$idPlazoNotas);
        return $this->db->get()->row_array();
    }
        
    /*
     * Get all plazonotas
     */
    function get_all_plazonotas()
    {
        $this->db->from('plazonotas pn');
        $this->db->join('semestreAcademico sa', 'pn.idSemestreAcademico = sa.idSemestreAcademico','left');
        $this->db->order_by('pn.idSemestreAcademico', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new plazonota
     */
    function add_plazonota($params)
    {
        $this->db->insert('plazonotas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plazonota
     */
    function update_plazonota($idPlazoNotas,$params)
    {
        $this->db->where('idPlazoNotas',$idPlazoNotas);
        return $this->db->update('plazonotas',$params);
    }
    
    /*
     * function to delete plazonota
     */
    function delete_plazonota($idPlazoNotas)
    {
        return $this->db->delete('plazonotas',array('idPlazoNotas'=>$idPlazoNotas));
    }
}
