<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Practica_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get practica by idPracticas
     */
    function get_practica($idPracticas)
    {
        return $this->db->get_where('practicas',array('idPracticas'=>$idPracticas))->row_array();
    }

    /*
     * Get Datos completos de una practica para la edicion
     */
    function get_all_practica($idPractica)
    {
        $this->db->from('practicas pr');
        $this->db->join('modulo m', 'pr.idModulo = m.idModulo','left');
        $this->db->join('estudiante e', 'pr.idEstudiante = e.idEstudiante','left');
        $this->db->join('persona p', 'e.idPersona = p.idPersona','left');
        $this->db->join('escuelaProfesional ep','m.idEscuelaProfesional = ep.idEscuelaProfesional','left');
        $this->db->where('pr.idPracticas',$idPractica);
        return $this->db->get()->row_array();
    }
        
    /*
     * Get all practicas
     */
    function get_all_practicas()
    {
        $this->db->order_by('idPracticas', 'desc');
        return $this->db->get('practicas')->result_array();
    }

    /*
     * Get all complete practicas/ datos de carera - nombres- 
     */
    function get_all_complete_practicas()
    {
        $this->db->from('practicas pr');
        $this->db->join('modulo m', 'pr.idModulo = m.idModulo','left');
        $this->db->join('estudiante e', 'pr.idEstudiante = e.idEstudiante','left');
        $this->db->join('persona p', 'e.idPersona = p.idPersona','left');
        $this->db->order_by('idPracticas', 'desc');
        $this->db->limit(30);
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new practica
     */
    function add_practica($params)
    {
        $this->db->insert('practicas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update practica
     */
    function update_practica($idPracticas,$params)
    {
        $this->db->where('idPracticas',$idPracticas);
        return $this->db->update('practicas',$params);
    }
    
    /*
     * function to delete practica
     */
    function delete_practica($idPracticas)
    {
        return $this->db->delete('practicas',array('idPracticas'=>$idPracticas));
    }
}
