<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Practica_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get practica by idPracticas
     */
    function get_practica($idPracticas)
    {
        return $this->db->get_where('practicas',array('idPracticas'=>$idPracticas))->row_array();
    }
        
    /*
     * Get all practicas
     */
    function get_all_practicas()
    {
        $this->db->order_by('idPracticas', 'desc');
        return $this->db->get('practicas')->result_array();
    }
        
    /*
     * function to add new practica
     */
    function add_practica($params)
    {
        $this->db->insert('practicas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update practica
     */
    function update_practica($idPracticas,$params)
    {
        $this->db->where('idPracticas',$idPracticas);
        return $this->db->update('practicas',$params);
    }
    
    /*
     * function to delete practica
     */
    function delete_practica($idPracticas)
    {
        return $this->db->delete('practicas',array('idPracticas'=>$idPracticas));
    }
}
