<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Semestreacademico_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get semestreacademico by idSemestreAcademico
     */
    function get_semestreacademico($idSemestreAcademico)
    {
        return $this->db->get_where('semestreacademico',array('idSemestreAcademico'=>$idSemestreAcademico))->row_array();
    }
        
    /*
     * Get all semestreacademico
     */
    function get_all_semestreacademico()
    {
        $this->db->order_by('idSemestreAcademico', 'desc');
        return $this->db->get('semestreacademico')->result_array();
    }
        
    /*
     * function to add new semestreacademico
     */
    function add_semestreacademico($params)
    {
        $this->db->insert('semestreacademico',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update semestreacademico
     */
    function update_semestreacademico($idSemestreAcademico,$params)
    {
        $this->db->where('idSemestreAcademico',$idSemestreAcademico);
        return $this->db->update('semestreacademico',$params);
    }
    
    /*
     * function to delete semestreacademico
     */
    function delete_semestreacademico($idSemestreAcademico)
    {
        return $this->db->delete('semestreacademico',array('idSemestreAcademico'=>$idSemestreAcademico));
    }
    function get_lastsemestreacademico(){
        $this->db->join('plazoMatricula pm', 'pm.idSemestreAcademico=sa.idSemestreAcademico','left');
        $this->db->order_by('sa.idSemestreAcademico', 'desc');
        $this->db->limit(1);
        return $this->db->get('semestreacademico sa')->row_array();
    }
}
