<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sexo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sexo by idSexo
     */
    function get_sexo($idSexo)
    {
        return $this->db->get_where('sexo',array('idSexo'=>$idSexo))->row_array();
    }
        
    /*
     * Get all sexo
     */
    function get_all_sexo()
    {
        $this->db->order_by('idSexo', 'asc');
        return $this->db->get('sexo')->result_array();
    }
        
    /*
     * function to add new sexo
     */
    function add_sexo($params)
    {
        $this->db->insert('sexo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sexo
     */
    function update_sexo($idSexo,$params)
    {
        $this->db->where('idSexo',$idSexo);
        return $this->db->update('sexo',$params);
    }
    
    /*
     * function to delete sexo
     */
    function delete_sexo($idSexo)
    {
        return $this->db->delete('sexo',array('idSexo'=>$idSexo));
    }
}
