<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipomatricula_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipomatricula by idtipoMatricula
     */
    function get_tipomatricula($idtipoMatricula)
    {
        return $this->db->get_where('tipoMatricula',array('idtipoMatricula'=>$idtipoMatricula))->row_array();
    }
        
    /*
     * Get all tipomatricula
     */
    function get_all_tipomatricula()
    {
        $this->db->order_by('idtipoMatricula', 'desc');
        return $this->db->get('tipoMatricula')->result_array();
    }
        
    /*
     * function to add new tipomatricula
     */
    function add_tipomatricula($params)
    {
        $this->db->insert('tipoMatricula',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipomatricula
     */
    function update_tipomatricula($idtipoMatricula,$params)
    {
        $this->db->where('idtipoMatricula',$idtipoMatricula);
        return $this->db->update('tipoMatricula',$params);
    }
    
    /*
     * function to delete tipomatricula
     */
    function delete_tipomatricula($idtipoMatricula)
    {
        return $this->db->delete('tipoMatricula',array('idtipoMatricula'=>$idtipoMatricula));
    }
}
