<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidaddidactica_has_matricula_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidaddidactica_has_matricula by unidadDidactica_idunidadDidactica
     */
    function get_unidaddidactica_has_matricula($unidadDidactica_idunidadDidactica)
    {
        return $this->db->get_where('unidadDidactica_has_matricula',array('unidadDidactica_idunidadDidactica'=>$unidadDidactica_idunidadDidactica))->row_array();
    }
        
    /*
     * Get all unidaddidactica_has_matricula
     */
    function get_all_unidaddidactica_has_matricula()
    {
        $this->db->order_by('unidadDidactica_idunidadDidactica', 'desc');
        return $this->db->get('unidadDidactica_has_matricula')->result_array();
    }
        
    /*
     * function to add new unidaddidactica_has_matricula
     */
    function add_unidaddidactica_has_matricula($params)
    {
        $this->db->insert('unidadDidactica_has_matricula',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidaddidactica_has_matricula
     */
    function update_unidaddidactica_has_matricula($unidadDidactica_idunidadDidactica,$params)
    {
        $this->db->where('unidadDidactica_idunidadDidactica',$unidadDidactica_idunidadDidactica);
        return $this->db->update('unidadDidactica_has_matricula',$params);
    }
    
    /*
     * function to delete unidaddidactica_has_matricula
     */
    function delete_unidaddidactica_has_matricula($unidadDidactica_idunidadDidactica)
    {
        return $this->db->delete('unidadDidactica_has_matricula',array('unidadDidactica_idunidadDidactica'=>$unidadDidactica_idunidadDidactica));
    }
    function get_all_unidaddidactica_has_idmatricula($idmatricula){
        $query = $this->db->query("SELECT * FROM unidaddidactica_has_matricula as udm RIGHT JOIN unidaddidactica as ud on ud.idUnidadDidactica=udm.unidadDidactica_idUnidadDidactica WHERE udm.matricula_idMatricula = ".$idmatricula."");

       return $query->result_array();
    }
}
