<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidaddidactica_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidaddidactica by idUnidadDidactica
     */
    function get_unidaddidactica($idUnidadDidactica)
    {
        return $this->db->get_where('unidaddidactica',array('idUnidadDidactica'=>$idUnidadDidactica))->row_array();
    }
        
    /*
     * Get all unidaddidactica
     */
    function get_all_unidaddidactica()
    {
        $this->db->order_by('idUnidadDidactica', 'desc');
        return $this->db->get('unidaddidactica')->result_array();
    }
        
    /*
     * function to add new unidaddidactica
     */
    function add_unidaddidactica($params)
    {
        $this->db->insert('unidaddidactica',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidaddidactica
     */
    function update_unidaddidactica($idUnidadDidactica,$params)
    {
        $this->db->where('idUnidadDidactica',$idUnidadDidactica);
        return $this->db->update('unidaddidactica',$params);
    }
    
    /*
     * function to delete unidaddidactica
     */
    function delete_unidaddidactica($idUnidadDidactica)
    {
        return $this->db->delete('unidaddidactica',array('idUnidadDidactica'=>$idUnidadDidactica));
    }
}
