<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by idUsuario
     */
    function get_usuario($idUsuario)
    {
        return $this->db->get_where('usuario',array('idUsuario'=>$idUsuario))->row_array();
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $this->db->order_by('idUsuario', 'desc');
        return $this->db->get('usuario')->result_array();
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($idUsuario,$params)
    {
        $this->db->where('idUsuario',$idUsuario);
        return $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($idUsuario)
    {
        return $this->db->delete('usuario',array('idUsuario'=>$idUsuario));
    }
    public function login($username,$password){
        $this->db->where("usuario",$username);
        $this->db->where("password",$password);

        $result=$this->db->get("usuario");
        if ($result->num_rows()>0) {
            return $result->row();
        }else{
            return false;
        }
    }
    function get_login( $user = null, $password = null ){
        $data = null;
        $loginResponse = null;
        $loginResponse = $this->db->query("SELECT * FROM usuario 
            WHERE usuario = ?  
            AND password = ? 
            AND idPermiso=2;",array($user,$password))->row_array();
        
        if ( empty($loginResponse) ) {
            $loginResponse = $this->db->query("SELECT * FROM usuario 
            WHERE usuario = ?  
            AND password = ? 
            AND idPermiso=1;;",array($user,$password))->row_array();
            if (!empty($loginResponse)) {
                $data["response"] = "success";
                $data["message"] = "Login Exitoso..!";
                $data["data"] = array(
                    "tipo"              => mb_strtolower('cliente'),
                    "idusuario"         => $loginResponse['idusuario'],
                    "nombrecompleto"    => $loginResponse['nombrecompleto'],
                    "usuario"           => $loginResponse['usuario'],
                    "dni"               => $loginResponse['dni'],
                );
            }else{
                $data["response"] = "error";
                $data["message"] = "La cuenta no existe..!";
                $data["data"] = array(
                    "tipo"          => null,
                );
            }
        }else{
            $data["response"] = "success";
            $data["message"] = "Login Exitoso..!";
            $data["data"] = array(
                    "tipo"          => mb_strtolower('admin'),
                    "idusuario"         => $loginResponse['idusuario'],
                    "nombrecompleto"    => $loginResponse['nombrecompleto'],
                    "usuario"           => $loginResponse['usuario'],
                    "dni"               => $loginResponse['dni'],
            );
        }
        var_dump($data);
        return $data;

    }
    public function logout(){
        $this->session->sess_destroy();
        redirect(base_url().'login');
    }

}
